language: python

virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
 - sudo ln /dev/null /dev/raw1394
install:
  - "pip install -r requirements.txt"

python:
  - "2.7"
script:
  - python run-tests.py
